source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
project 'MemoryJar'
use_frameworks!

target 'MemoryJar_Example' do
  pod 'MemoryJar', :path => '../'

  target 'MemoryJar_Tests' do
    inherit! :search_paths


  end
end
